### ISSUE TITLE
questions about roomhub

### ISSUE THREAD

**Issue by tfaureperso** [aetas/RoomHub#13]
very nice project
I want to build something similar for my home with esp32 in wired and wireless mode
I don't know if it's the right place to ask questions.

So i have several questions about the system :

- for the box itself if i understand clearly in contain the 2 boards (main and i/o) what's it dimension? do you use a premade box or made you own?
- for the I/O connectors why do you use rj45 and not groove or others?
- for power supply in case of use as an alarm system or for an outside use is it possible to use with battery?

That's all for now
Thank's advance
Thierry

**Comment by jozala** [comment]
Hi Thierry,
Thanks for your questions.

> for the box itself if i understand clearly in contain the 2 boards (main and i/o) what's it dimension? do you use a premade box or made you own?

There are two boards in the box. You can see them [in documentation](https://aetas.github.io/RoomHub/hardware/board-layout/). 
Mainboard is 200x134mm and I/O board is 179x63mm. Box is around 245x240x50mm. I got it from local producer. They have some premade sizes and they made custom cut outs for me. 

> for the I/O connectors why do you use rj45 and not groove or others?

I have UTP cables everywhere to connect relays modules, reed switches, move sensors etc. So I naturally went into RJ45-like solutions. I've been considering screw connectors and tried Krone LSA connectors and reversed patch panels, but it was all too clumsy and cumbersome. 
With RJ45 connectors, some of the wires are unused, but it makes everything easier for me and more stable.

> for power supply in case of use as an alarm system or for an outside use is it possible to use with battery?

I haven't tried to use it with battery. In theory you could use power bank to power it. It is powered with 5V DC. Maybe this could work like a UPS. However, I have never considered using it that way and never measured the power consumption. From what I know ESP32 with WiFi needs quite a lot of current.
I am using RoomHub with some motion sensors and relays which are connected with more than 10 meters long cables. For outside use you could keep the device inside and only put sensors outside.

I hope it answer your questions. Let me know if you have some more.
